import React from 'react';
import {createRoot} from 'react-dom/client';
import {listMeetings,saveMeeting,deleteMeeting,type Meeting} from './storage';
import './style.css';
import {startRecording,downloadRecording,recoverRecording,supported} from './recording';
const departments=['Chung','Bán hàng','Sản xuất','Marketing','Thiết kế','Vận hành','Tài chính'];
function App(){
 const [name,setName]=React.useState('');const [department,setDepartment]=React.useState('Chung');
 const [meetings,setMeetings]=React.useState<Meeting[]>([]);const [error,setError]=React.useState('');const [ready,setReady]=React.useState(false);
 const [editing,setEditing]=React.useState<string|null>(null);
 const [recorder,setRecorder]=React.useState<MediaRecorder|null>(null);
 const [audio,setAudio]=React.useState<Blob|null>(null);
 const [recordingError,setRecordingError]=React.useState('');
 async function begin(){setRecordingError('');setAudio(null);try{const r=await startRecording(setAudio,setRecordingError);setRecorder(r)}catch{setRecordingError('Không thể mở microphone. Hãy cấp quyền và thử lại.')}}
 async function recover(){const session=localStorage.getItem('da-meeting-last-audio-session');if(!session){setRecordingError('Chưa có phiên ghi âm để khôi phục.');return}try{const blob=await recoverRecording(session);if(!blob.size)throw Error('empty');setAudio(blob);setRecordingError('Đã tìm thấy các đoạn âm thanh được lưu. Hãy tải về ngay.')}catch{setRecordingError('Không tìm thấy đoạn âm thanh có thể khôi phục.')}}
 function stop(){if(recorder&&recorder.state!=='inactive'){recorder.stop();setRecorder(null)}}
 async function refresh(){try{setMeetings(await listMeetings());setReady(true);setError('')}catch{setError('Không mở được kho lưu trữ trên trình duyệt. Kiểm tra chế độ riêng tư hoặc dung lượng.');setReady(false)}}
 React.useEffect(()=>{void refresh()},[]);
 async function submit(e:React.FormEvent){e.preventDefault();if(!name.trim())return;try{await saveMeeting({id:editing||crypto.randomUUID(),title:name.trim(),department,created_at:editing?meetings.find(m=>m.id===editing)?.created_at||new Date().toISOString():new Date().toISOString()});setName('');setEditing(null);await refresh()}catch{setError('Không lưu được cuộc họp trên thiết bị.');}}
 function edit(m:Meeting){setEditing(m.id);setName(m.title);setDepartment(m.department);window.scrollTo({top:0,behavior:'smooth'})}
 async function remove(m:Meeting){if(!window.confirm('Xóa cuộc họp này khỏi thiết bị?'))return;try{await deleteMeeting(m.id);await refresh()}catch{setError('Không xóa được cuộc họp.')}}
 function exportBackup(){const blob=new Blob([JSON.stringify({format:'da-meeting-v03',meetings},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='da-meeting-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 async function importBackup(file:File|undefined){if(!file)return;try{if(file.size>10_000_000)throw Error('large');const parsed=JSON.parse(await file.text());if(parsed?.format!=='da-meeting-v03'||!Array.isArray(parsed.meetings)||parsed.meetings.length>10000)throw Error('format');for(const m of parsed.meetings){if(typeof m.id!=='string'||typeof m.title!=='string'||typeof m.department!=='string'||typeof m.created_at!=='string'||m.title.length>200)throw Error('data')}if(!window.confirm('Nhập dữ liệu và ghi đè những cuộc họp trùng ID?'))return;for(const m of parsed.meetings)await saveMeeting({id:m.id,title:m.title,department:m.department,created_at:m.created_at});await refresh()}catch{setError('Tệp sao lưu không hợp lệ hoặc không thể nhập.')}}
 return <main><header><strong>D&A <span>Meeting</span></strong><small>POWERED BY HOANGGIA AI</small></header><section className="hero"><p className="eyebrow">AI EXECUTIVE SECRETARY · V0.4 RECORDING PREVIEW</p><h1>Cuộc họp rõ ràng.<br/>Dữ liệu trong tầm tay.</h1><p>Tạo và quản lý cuộc họp ngay trên thiết bị, không cần máy chủ hay API trả phí.</p><div className="status"><span className={'dot '+(ready?'connected':'offline')}/>{ready?'Lưu cục bộ trên thiết bị':'Kho dữ liệu chưa sẵn sàng'}</div>
 <div className="panel"><h2>{editing?'Chỉnh sửa cuộc họp':'Tạo cuộc họp'}</h2><form onSubmit={submit}><label>Tên cuộc họp<input aria-label="Tên cuộc họp" placeholder="Ví dụ: Họp showroom" value={name} maxLength={200} onChange={e=>setName(e.target.value)}/></label><label>Bộ phận<select value={department} onChange={e=>setDepartment(e.target.value)}>{departments.map(d=><option key={d}>{d}</option>)}</select></label><button disabled={!ready}>{editing?'Cập nhật':'Lưu cuộc họp'}</button></form>{editing&&<button className="secondary" onClick={()=>{setEditing(null);setName('')}}>Hủy chỉnh sửa</button>}{error&&<p role="alert" className="error">{error}</p>}<p className="hint">Dữ liệu chỉ lưu trong trình duyệt này. Hãy sao lưu thường xuyên; xóa dữ liệu Safari/Chrome có thể làm mất cuộc họp.</p></div>
 <div className="panel"><h2>Ghi âm thử nghiệm</h2><p className="hint">Chỉ ghi khi đã được mọi người tham gia đồng ý. Âm thanh được lưu từng đoạn vào thiết bị. Không bảo đảm ghi liên tục 5–8 giờ, đặc biệt trên iPhone; các đoạn chưa kịp lưu có thể bị mất. Hãy dùng thiết bị ghi âm chuyên dụng cho cuộc họp quan trọng.</p><div className="actions"><button disabled={!supported()||!!recorder} onClick={()=>void begin()}>Bắt đầu ghi âm</button><button className="secondary" disabled={!recorder} onClick={stop}>Dừng ghi</button><button className="secondary" disabled={!audio} onClick={()=>audio&&downloadRecording(audio)}>Tải bản ghi</button><button className="secondary" disabled={!!recorder} onClick={()=>void recover()}>Khôi phục đoạn đã lưu</button></div>{recorder&&<p role="status">Đang ghi âm — giữ màn hình và trình duyệt hoạt động.</p>}{audio&&<p role="status">Đã ghi xong. Tải tệp về ngay để tránh mất dữ liệu.</p>}{recordingError&&<p role="alert" className="error">{recordingError}</p>}</div><div className="panel"><div className="panel-head"><h2>Cuộc họp ({meetings.length})</h2><button className="secondary" onClick={exportBackup} disabled={!ready}>Xuất sao lưu</button></div><label className="import">Nhập sao lưu (.json)<input type="file" accept=".json,application/json" onChange={e=>{void importBackup(e.target.files?.[0]);e.target.value=''}}/></label>{meetings.length?meetings.map(m=><div className="meeting" key={m.id}><strong>{m.title}</strong><span>{m.department} · {new Date(m.created_at).toLocaleString('vi-VN')}</span><div className="actions"><button className="secondary" onClick={()=>edit(m)}>Sửa</button><button className="secondary" onClick={()=>void remove(m)}>Xóa</button></div></div>):<p className="hint">Chưa có cuộc họp.</p>}</div><p className="hint">Ghi âm chỉ ở mức thử nghiệm; phiên âm và 17 AI Expert chưa khả dụng.</p></section><footer>© 2026 HOANGGIA AI · D&A Meeting · Browser-first</footer></main>
}
createRoot(document.getElementById('root')!).render(<App/>);
