import React from 'react';
import {createRoot} from 'react-dom/client';
import {listMeetings,saveMeeting,deleteMeeting,type Meeting} from './storage';
import './style.css';
import {startRecording,downloadRecording,recoverRecording,supported,MAX_RECORDING_MS,formatDuration,storageEstimate,requestPersistentStorage,downloadSavedChunks} from './recording';

const departments=['Chung','Bán hàng','Sản xuất','Marketing','Thiết kế','Vận hành','Tài chính'];
function App(){
 const [name,setName]=React.useState('');const [department,setDepartment]=React.useState('Chung');
 const [meetings,setMeetings]=React.useState<Meeting[]>([]);const [error,setError]=React.useState('');const [ready,setReady]=React.useState(false);
 const [editing,setEditing]=React.useState<string|null>(null);
 const [recorder,setRecorder]=React.useState<MediaRecorder|null>(null);
 const [audio,setAudio]=React.useState<Blob|null>(null);
 const [recordingError,setRecordingError]=React.useState('');
 const [startedAt,setStartedAt]=React.useState<number|null>(null);
 const [elapsed,setElapsed]=React.useState(0);
 const [capacity,setCapacity]=React.useState('');
 React.useEffect(()=>{if(startedAt===null)return;const timer=setInterval(()=>{const delta=Date.now()-startedAt;setElapsed(delta);if(delta>=MAX_RECORDING_MS){setRecorder(r=>{if(r&&r.state!=='inactive')r.stop();return null});setStartedAt(null)}},1000);return()=>clearInterval(timer)},[startedAt]);
 async function checkCapacity(){const e=await storageEstimate();const free=e.quota!==undefined&&e.usage!==undefined?e.quota-e.usage:undefined;setCapacity(free===undefined?'Dung lượng khả dụng: chưa xác định':'Dung lượng ước tính còn: '+Math.round(free/1048576)+' MB');if(free!==undefined&&free<650*1048576)setRecordingError('Cảnh báo: dung lượng trống có thể không đủ cho 10 tiếng.')}
 async function exportParts(){const session=localStorage.getItem('da-meeting-last-audio-session');if(!session)return;try{const count=await downloadSavedChunks(session);setRecordingError('Đã yêu cầu tải '+count+' phần. Lưu ý: các đoạn MediaRecorder tách riêng có thể không phát độc lập; cần kiểm tra trên thiết bị. Trình duyệt có thể chặn tải nhiều tệp.')}catch{setRecordingError('Không xuất được các đoạn âm thanh.')}}
 async function begin(){setRecordingError('');setAudio(null);try{await requestPersistentStorage();await checkCapacity();const r=await startRecording(setAudio,setRecordingError);setRecorder(r);setStartedAt(Date.now());setElapsed(0)}catch{setRecordingError('Không thể mở microphone. Hãy cấp quyền và thử lại.')}}
 function stop(){if(recorder&&recorder.state!=='inactive'){recorder.stop();setRecorder(null);setStartedAt(null)}}
 async function recover(){const session=localStorage.getItem('da-meeting-last-audio-session');if(!session){setRecordingError('Chưa có phiên ghi âm để khôi phục.');return}try{const blob=await recoverRecording(session);if(!blob.size)throw Error('empty');setAudio(blob);setRecordingError('Đã tìm thấy các đoạn được lưu. Hãy tải về ngay.')}catch{setRecordingError('Không tìm thấy đoạn âm thanh có thể khôi phục.')}}

 async function refresh(){try{setMeetings(await listMeetings());setReady(true);setError('')}catch{setError('Không mở được kho lưu trữ trên trình duyệt. Kiểm tra chế độ riêng tư hoặc dung lượng.');setReady(false)}}
 React.useEffect(()=>{void refresh()},[]);
 async function submit(e:React.FormEvent){e.preventDefault();if(!name.trim())return;try{await saveMeeting({id:editing||crypto.randomUUID(),title:name.trim(),department,created_at:editing?meetings.find(m=>m.id===editing)?.created_at||new Date().toISOString():new Date().toISOString()});setName('');setEditing(null);await refresh()}catch{setError('Không lưu được cuộc họp trên thiết bị.');}}
 function edit(m:Meeting){setEditing(m.id);setName(m.title);setDepartment(m.department);window.scrollTo({top:0,behavior:'smooth'})}
 async function remove(m:Meeting){if(!window.confirm('Xóa cuộc họp này khỏi thiết bị?'))return;try{await deleteMeeting(m.id);await refresh()}catch{setError('Không xóa được cuộc họp.')}}
 function exportBackup(){const blob=new Blob([JSON.stringify({format:'da-meeting-v03',meetings},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='da-meeting-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 async function importBackup(file:File|undefined){if(!file)return;try{if(file.size>10_000_000)throw Error('large');const parsed=JSON.parse(await file.text());if(parsed?.format!=='da-meeting-v03'||!Array.isArray(parsed.meetings)||parsed.meetings.length>10000)throw Error('format');for(const m of parsed.meetings){if(typeof m.id!=='string'||typeof m.title!=='string'||typeof m.department!=='string'||typeof m.created_at!=='string'||m.title.length>200)throw Error('data')}if(!window.confirm('Nhập dữ liệu và ghi đè những cuộc họp trùng ID?'))return;for(const m of parsed.meetings)await saveMeeting({id:m.id,title:m.title,department:m.department,created_at:m.created_at});await refresh()}catch{setError('Tệp sao lưu không hợp lệ hoặc không thể nhập.')}}
 return <main><header><strong>D&A <span>Meeting</span></strong><small>POWERED BY HOANGGIA AI</small></header><section className="hero"><p className="eyebrow">AI EXECUTIVE SECRETARY · V0.6 LONG RECORDING PREVIEW</p><h1>Cuộc họp rõ ràng.<br/>Dữ liệu trong tầm tay.</h1><p>Tạo và quản lý cuộc họp ngay trên thiết bị, không cần máy chủ hay API trả phí.</p><div className="status"><span className={'dot '+(ready?'connected':'offline')}/>{ready?'Lưu cục bộ trên thiết bị':'Kho dữ liệu chưa sẵn sàng'}</div>
 <div className="panel"><h2>{editing?'Chỉnh sửa cuộc họp':'Tạo cuộc họp'}</h2><form onSubmit={submit}><label>Tên cuộc họp<input aria-label="Tên cuộc họp" placeholder="Ví dụ: Họp showroom" value={name} maxLength={200} onChange={e=>setName(e.target.value)}/></label><label>Bộ phận<select value={department} onChange={e=>setDepartment(e.target.value)}>{departments.map(d=><option key={d}>{d}</option>)}</select></label><button disabled={!ready}>{editing?'Cập nhật':'Lưu cuộc họp'}</button></form>{editing&&<button className="secondary" onClick={()=>{setEditing(null);setName('')}}>Hủy chỉnh sửa</button>}{error&&<p role="alert" className="error">{error}</p>}<p className="hint">Dữ liệu chỉ lưu trong trình duyệt này. Hãy sao lưu thường xuyên; xóa dữ liệu Safari/Chrome có thể làm mất cuộc họp.</p></div>
 <div className="panel"><h2>Ghi âm trực tiếp · thử nghiệm</h2><p className="hint">Chỉ ghi khi mọi người đã đồng ý. Tự lưu các đoạn âm thanh trên thiết bị, nhưng iPhone có thể ngừng ghi khi khóa màn hình hoặc chuyển ứng dụng. Mục tiêu tối đa 10 tiếng trên trình duyệt còn hoạt động; không bảo đảm ghi đủ 10 tiếng. Hãy tải bản ghi đầy đủ về sau khi dừng. Bản sao lưu JSON không chứa âm thanh.</p><div className="actions"><button disabled={!supported()||!!recorder} onClick={()=>void begin()}>Bắt đầu ghi</button><button className="secondary" disabled={!recorder} onClick={stop}>Dừng ghi</button><button className="secondary" disabled={!audio} onClick={()=>audio&&downloadRecording(audio)}>Tải bản ghi</button><button className="secondary" disabled={!!recorder} onClick={()=>void recover()}>Khôi phục đoạn đã lưu</button><button className="secondary" disabled={!!recorder} onClick={()=>void exportParts()}>Xuất thành nhiều phần</button></div>{recorder&&<p role="status">Đang ghi {formatDuration(elapsed)} / 10:00:00 — giữ trình duyệt hoạt động.</p>}<p className="hint">{capacity}</p>{recordingError&&<p role="alert">{recordingError}</p>}</div><div className="panel"><div className="panel-head"><h2>Cuộc họp ({meetings.length})</h2><button className="secondary" onClick={exportBackup} disabled={!ready}>Xuất sao lưu</button></div><label className="import">Nhập sao lưu (.json)<input type="file" accept=".json,application/json" onChange={e=>{void importBackup(e.target.files?.[0]);e.target.value=''}}/></label>{meetings.length?meetings.map(m=><div className="meeting" key={m.id}><strong>{m.title}</strong><span>{m.department} · {new Date(m.created_at).toLocaleString('vi-VN')}</span><div className="actions"><button className="secondary" onClick={()=>edit(m)}>Sửa</button><button className="secondary" onClick={()=>void remove(m)}>Xóa</button></div></div>):<p className="hint">Chưa có cuộc họp.</p>}</div><p className="hint">Ghi âm đang thử nghiệm; phiên âm và 17 AI Expert chưa khả dụng.</p></section><footer>© 2026 HOANGGIA AI · D&A Meeting · Browser-first</footer></main>
}
createRoot(document.getElementById('root')!).render(<App/>);
